package com.whh.spring.boot.dao;

import com.whh.spring.boot.model.CmUser;
import com.whh.spring.boot.model.CmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int countByExample(CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int deleteByExample(CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int insert(CmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int insertSelective(CmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    List<CmUser> selectByExample(CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    CmUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmUser record, @Param("example") CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmUser record, @Param("example") CmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CM_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmUser record);

    List<CmUser> selectUsers();

    Boolean countUser();
}